vim.cmd("let g:netrw_banner = 0")
vim.g.mapleader = " "
vim.o.number = true
vim.o.relativenumber = true
vim.o.wrap = false
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.o.swapfile = false
vim.o.backup = false
vim.o.undofile = true
-- vim.o.winborder = "rounded"
vim.o.signcolumn = "yes"
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.incsearch = true
vim.o.inccommand = "split"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.termguicolors = true
vim.o.background = "dark"
vim.o.scrolloff = 8
vim.o.splitright = true
vim.o.splitbelow = true
vim.opt.isfname:append("@-@")
vim.o.updatetime = 50
vim.opt.clipboard:append("unnamedplus")
vim.o.hlsearch = true
vim.o.mouse = "a"
vim.o.completeopt = "menu,menuone,noselect"
vim.g.editorconfig = true
